### ISSUE TITLE
No information anymore about the jupyter notebook examples

### ISSUE THREAD

**Issue by mbrunel** [mithril-security/blindai#100]
## Description
There used to be some kind of tutorial about how to use them. But not anymore, so it might be difficult to set up the proper environment

## Why this modification is needed?
Because they are awesome otherwise

## What documents need to be updated

- [ ] Main README
- [ ] We probably a new document dedicated to the jupyter notebooks usage is needed

## Checklist

This issue concerns the documentation

**Comment by JoFrost** [comment]
What are you referring to? I don't understand what you mean regarding the missing tutorials

**Comment by mbrunel** [comment]
Well I just couldn't find any info about how to run the notebooks. Which is a problem, because it's actually not that simple, since you need to run a specific docker container.
