### ISSUE TITLE
server: Remove SSH dependencies

### ISSUE THREAD

**Issue by cchudant** [mithril-security/blindai#11]
There are some `Cargo.lock` files that still use SSH to pull in dependencies
One example of it is [server/inference-server/network/sgx/rpc/Cargo.lock](https://github.com/mithril-security/blindai/blob/master/server/inference-server/network/sgx/rpc/Cargo.lock)

We should change them to use HTTPS

**Comment by JoFrost** [comment]
Noted, thanks for the report. Will be fixed ASAP

**Comment by JoFrost** [comment]
Fixed in commit 106a857ed52a20a62b879147b0440279ac8fa32f.
