### ISSUE TITLE
Whisper example missing NNDecodingTask definition

### ISSUE THREAD

**Issue by keren-riverside** [mithril-security/blindai#143]
## Description

I am going through the whisper BlindAI example in ``examples/whisper/BlindAI_Whisper.ipynb`` and one of the classes used -- ``NNDecodingTask`` -- is not defined in the notebook. Can the definition of this class be added so that it will be possible to export different Whisper models (small, large, multi-language etc)?

## Why this modification is needed?

Great tutorial that can't be followed 100%...

## What documents need to be updated
 - [ ] examples/whisper/BlindAI_Whisper.ipynb

**Comment by JoFrost** [comment]
FYI, the fixed notebook has been pushed on the repo, you can find it here: 
https://github.com/mithril-security/blindai/blob/master/examples/whisper/BlindAI_Whisper.ipynb
