### ISSUE TITLE
Undefined Parameter in docs/docs/how-to-guides/covid_net_confidential.ipynb 

### ISSUE THREAD

**Issue by pKap4** [mithril-security/blindai#181]
On multiple occasions, during the function call of blindai.client.connect, the parameter mentioned is hazmat_http_on_untrusted_port, but the parameter should be hazmat_http_on_unattested_port, as per the docs at https://blindai.mithrilsecurity.io/en/latest/blindai/core.html

Error:
<img width="543" alt="untrusted_error" src="https://github.com/mithril-security/blindai/assets/91935893/d44b92ea-a2c8-4a89-86ef-4cda57782d40">

Solution:
<img width="499" alt="unattested_solution" src="https://github.com/mithril-security/blindai/assets/91935893/ea767455-5480-4f49-90cc-ff6939c617c1">

**Comment by JoFrost** [comment]
Hello @pKap4 and thank you for reporting this issue!
I just pushed a fix for the corresponding how-to. This how-to was not updated after a refactoring we did on the last version. It should now work as expected.
