### ISSUE TITLE
Erroneous positional argument in docs/docs/how-to-guides/covid_net_confidential.ipynb

### ISSUE THREAD

**Issue by pKap4** [mithril-security/blindai#182]
The client.run_model function passes the model id and input tensor batch as positional arguments, but does so incorrectly as the first two arguments of said function are the model id and the model hash. Hence there is a need to explicitly mention that the input tensor object is passed to the input_tensors argument.

Error:
<img width="785" alt="implicit_parameter_passed_error" src="https://github.com/mithril-security/blindai/assets/91935893/080de2ed-4b76-4372-a030-cfcb7af954dd">

Solution:
![image](https://github.com/mithril-security/blindai/assets/91935893/050b9ce3-2a8f-47f7-b35f-82127a5367bc)

**Comment by JoFrost** [comment]
Issue fixed as well, thanks!
