### ISSUE TITLE
Not able to run BlindAI server on Azure DCsv3 VM

### ISSUE THREAD

**Issue by ajay-fuji** [mithril-security/blindai#194]
Hi

I have been trying to run BlindAI server on azure DCsv3 VM by following documentation from [here](https://blindai.mithrilsecurity.io/en/latest/docs/tutorials/core/installation/). I have tried deployment on Azure DCsv3 as well as on-premises deployment guide, but nothing works. 

Machine Config - 
- Standard DC2s v3 (2 vcpus, 16 GiB memory)

Command - 
```bash
 sudo docker run -it -e BLINDAI_AZURE_DCS3_PATCH=1 -p 9923:9923 -p 9924:9924 --device /dev/sgx/enclave --device /dev/sgx/provision  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket mithrilsecuritysas/blindai-server:latest /root/start.sh
```
Output - 
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: AesmCode(ServiceUnavailable_30)', remote_attestation_sgx/src/quote_generation.rs:23:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

> PCCS@1.15.0 start /opt/intel/sgx-dcap-pccs
> node pccs_server.js "pm2"

2024-05-30 05:03:07.939 [info]: DB Migration (Ver.0 -> 1) -- Start
2024-05-30 05:03:07.944 [info]: DB Migration -- Done.
2024-05-30 05:03:07.975 [info]: DB Migration (Ver.1 -> 2) -- Start
2024-05-30 05:03:07.980 [info]: DB Migration -- Done.
2024-05-30 05:03:08.014 [info]: DB Migration (Ver.2 -> 3) -- Start
2024-05-30 05:03:08.018 [info]: DB Migration -- Done.
2024-05-30 05:03:08.083 [info]: HTTPS Server is running on: https://localhost:8081
Starting BlindAI server...
BlindAI telemetry is enabled
Error: http://127.0.0.1:11000/get_target_info: Connection Failed: Connect error: connection refused (os error 111)

Caused by:
    connection refused (os error 111)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
Attaching debugger
Error on exec SGX enclave
 Enclave panicked..
```

Also, in step [Then you'll have to open the ports used by BlindAI: default ports 9923 and 9924](https://blindai.mithrilsecurity.io/en/latest/docs/tutorials/core/installation/#:~:text=Then%20you%27ll%20have%20to%20open%20the%20ports%20used%20by%20BlindAI%3A%20default%20ports%209923%20and%209924), it's opening ports 50051 and 50052; however, the default port for BlindAI is 9923 and 9924. What is the reason for opening inbound ports 50051 and 50052?

**Comment by darshanp4** [comment]
@ShannonSD @clauverjat can you please help to look at this issue?

**Comment by ShannonSD** [comment]
Hi @ajay-fuji and @darshanp4,

Thank you for trying out BlindAI. I think the incorrect ports being opened is because the docker image is based on an older version of BlindAI. We switched to using the fortanix sdk a while ago but seem to not have released a corresponding docker image.

Could you try building the enclave on the Azure VM using the sources as described here: [build server from source](https://blindai.mithrilsecurity.io/en/latest/docs/advanced/build-from-sources/server/) ?

Let us know if you run into any issues and we'll take a closer look.

**Comment by ajay-fuji** [comment]
Thankyou @ShannonSD. 
We will try building form source.
One question, in which layer fortanix sdk comes in BlindAI software stack?

**Comment by xoxruns** [comment]
Hello @ajay-fuji , 

To answer your question, the fortanix SDK is used to communicate with the SGX enclave. There is other SDKs that could be used such as [https://github.com/apache/incubator-teaclave-sgx-sdk](https://github.com/apache/incubator-teaclave-sgx-sdk) or the intel's [https://github.com/intel/linux-sgx/tree/main/sdk](https://github.com/intel/linux-sgx/tree/main/sdk). 

For the current version of blindAI, fortanix's SDK is used as the backbone for Intel SGX. 

let me know if I can close this issue.

**Comment by ajay-fuji** [comment]
Thanks for the response @gemini-15 .
My queries are answered, and we can close this issue for now. Will reopen or create a new query for any future discussion. Thanks
