### ISSUE TITLE
Execution exports

### ISSUE THREAD

**Issue by cchudant** [mithril-security/blindai#37]
## Description

For the Signed Responses feature (#13) to be useful, we need a way to export and validate execution proofs.

Here is the proposed API:
```py
response = client.run_model(run_inputs, sign=True)
response.save_to_file("./execution_proof.json")
```

```py
from blindai.client import load_execution_file

response = load_execution_file("./proof_of_execution.json")
response.validate(policy_file="./policy.toml") # throws if invalid or execution is not signed
print("The proof is valid!")
```

We should also have these functions:

```py
response.export_binary() :: bytes
from blindai.client import load_execution_binary
response = load_execution_binary(a :: bytes)
```

### Unanswered questions
- Json? CBOR is probably a better choice
- Should `save_to_file` work when sign=False?

## Motivation and Context
For the Signed Responses feature (#13) to be useful, we need a way to export execution proofs.

## Affected Features
Signed Responses feature (#13)

## Test Plans
Add tests and unit-tests.

## Additional Information
None

## Checklist
- [x] This issue concerns BlindAI Client
- [ ] This issue concerns BlindAI Server

**Comment by cchudant** [comment]
I want your thoughts on that @JoFrost before assigning it to myself and start working on it

**Comment by JoFrost** [comment]
I am not against it. Go for it,

**Comment by JoFrost** [comment]
And yes, CBOR is the way to go imo

**Comment by cchudant** [comment]
Currently working on it :)
