### ISSUE TITLE
Load policy and certificate from bytes

### ISSUE THREAD

**Issue by cchudant** [mithril-security/blindai#38]
## Description
Add a way to load policy.toml and certificate from bytes instead of a file

## Motivation and Context
Quick and easy feature, should improve our API surface.

## Test plans
Add unit tests.

## Additional Information
None.

## Checklist
- [x] This issue concerns BlindAI Client
- [ ] This issue concerns BlindAI Server

**Comment by clauverjat** [comment]
Reopening as it seems to me that this problem has not been solved.
The connect() function only supports loading a policy and a certificate from path, see https://github.com/mithril-security/blindai/blob/master/client/blindai/client.py#L394
