### ISSUE TITLE
Automate the generation of the client API reference

### ISSUE THREAD

**Issue by CerineBnsd** [mithril-security/blindai#51]
## Description
The client API reference should be automatically generated from docstrings in the package files. 

## Why this modification is needed?
It's not practicle to rewrite it everytime we do changes, it can also have a better look this way.

## What documents need to be updated

- [X] BlindAI Client CHANGELOG
- [X] Python Docstrings (May need to change the style of the comments)
- [X] Client API reference

## Additional Information
The existing toole may generate the documentatoin in form of HTML pages => A website, should we be restricted to the once who produce markdown files instead?  So that they can always be included directly in the gitbook, or we can have a website that will be linked there? 

## Checklist

- [X] This issue concerns BlindAI Client
- [ ] This issue concerns BlindAI Server

**Comment by JoFrost** [comment]
Bumping this issue, as it will become a priority with the future releases

**Comment by mbrunel** [comment]
I think we can close it now right?

**Comment by JoFrost** [comment]
Yep!
