### ISSUE TITLE
Client notebook docker does not seem to work on WSL

### ISSUE THREAD

**Issue by cchudant** [mithril-security/blindai#58]
## Description

The command `docker run --network host mithrilsecuritysas/blindai-client-demo` does not work on WSL (tested on matthias' computer)
It runs fine but the notebook cannot be accessed on the browser.
This is probably due to `--network host` sharing the network with WSL and not Windows entirely, but I'm not sure, I don't know how WSL works.

I don't know how to fix it, and I don't have any windows machine on hand.

Also, we were talking with Daniel about packaging the server in the blindai-client-demo docker image directly. This could be awesome for getting started with the project, and that would allow us to sidestep this issue entirely.

**Comment by JoFrost** [comment]
Sounds good
