### ISSUE TITLE
Connection Error: client.connect_server(..) - Hardware mode - CovidNet Example

### ISSUE THREAD

**Issue by Alexis-CAPON** [mithril-security/blindai#59]
Hi,
I encountered some problems while implementing your framework in hardware with the CovidNet example that you provide.
Do you think of anything I forgot?

## Description

I have an error that I cannot explain during the step of connecting the client to the server.

## Blindai Versions

- BlindAI Client : "0.2.0"
- BlindAI Server : "0.2.2"

## Additional Information

- Ubuntu
- Version: 20.04.1 
- Package Manager Version: pip 22.0.4
- Language version : Python 3.8.10
- Kernel : 5.13.0-40-generic

## Screenshots:

![image](https://user-images.githubusercontent.com/72978378/165542592-e32a6bc2-f39b-4216-884e-adfcf5ac0e98.png)
![Capture d’écran du 2022-04-27 16-32-42](https://user-images.githubusercontent.com/72978378/165544219-367cb682-f8dd-448a-9455-d5e0ddac7290.png)

**Comment by Alexis-CAPON** [comment]
Thank you for your reply.
No I don't, that's why I used isgx

**Comment by JoFrost** [comment]
Got it. In that case, this is the reason you have this error.
SGX1 (without Flexible Launch Control) does not implement security features we rely on, this is why we cannot support it. 
If you want to try on the hardware mode anyway, I would suggest to try on an Azure Confidential Computing VM. You can try for free and get started quickly. You can find here a tutorial on how to get started quickly: https://docs.mithrilsecurity.io/getting-started/cloud-deployment/azure-dcsv2

**Comment by Alexis-CAPON** [comment]
Alright, thank you very much!
